name: tuning_env
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - gmp=6.3.0
  - intel-openmp=2023.1.0
  - ld_impl_linux-64=2.40
  - libabseil=20250127.0
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libprotobuf=5.29.3
  - libstdcxx-ng=11.2.0
  - libtorch=2.5.1
  - libuuid=1.41.5
  - libuv=1.48.0
  - mkl=2023.1.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - ncurses=6.4
  - numpy-base=1.26.4
  - openssl=3.0.16
  - python=3.11.11
  - pytorch=2.5.1
  - readline=8.2
  - sleef=3.5.1
  - sqlite=3.45.3
  - tbb=2021.8.0
  - tk=8.6.14
  - typing_extensions=4.12.2
  - xz=5.6.4
  - yaml=0.2.5
  - zlib=1.2.13
  - pip
  - pip:
    - optuna>=4.0.0,<5.0.0
    - argon2-cffi==23.1.0
    - argon2-cffi-bindings==21.2.0
    - borch==0.1.6
    - botorch==0.9.3
    - certifi==2025.4.26
    - cffi==1.17.1
    - charset-normalizer==3.4.1
    - click==8.1.8
    - contourpy==1.3.2
    - cycler==0.12.1
    - deprecated==1.2.13
    - environs==9.5.0
    - filelock==3.17.0
    - fonttools==4.57.0
    - fsspec==2024.12.0
    - gmpy2==2.2.1
    - gpytorch==1.11
    - grpcio==1.58.0
    - h5py==3.13.0
    - idna==3.10
    - importlib-metadata==8.5.0
    - jaxtyping==0.3.2
    - jinja2==3.1.6
    - joblib==1.4.2
    - kiwisolver==1.4.8
    - linear-operator==0.5.1
    - markdown-it-py==3.0.0
    - markupsafe==3.0.2
    - marshmallow==3.14.1
    - matplotlib==3.10.3
    - mdurl==0.1.2
    - milvus-lite==2.4.12
    - minio==7.2.15
    - mkl-fft==1.3.11
    - mkl-random==1.2.8
    - mkl-service==2.4.0
    - mpmath==1.3.0
    - multipledispatch==1.0.0
    - mypy-extensions==1.1.0
    - networkx==3.4.2
    - numpy==1.26.4
    - opentelemetry-api==1.30.0
    - opt-einsum==3.4.0
    - packaging==25.0
    - pandas==2.2.3
    - pillow==11.2.1
    - pip==25.0
    - protobuf==6.30.2
    - pycparser==2.22
    - pycryptodome==3.22.0
    - pygments==2.19.1
    - pymilvus==2.3.1
    - pyparsing==3.2.3
    - pyre-extensions==0.0.32
    - pyro-api==0.1.2
    - pyro-ppl==1.9.1
    - python-dateutil==2.9.0.post0
    - python-dotenv==1.1.0
    - pytz==2025.2
    - pyyaml==6.0.2
    - requests==2.32.3
    - rich==14.0.0
    - scikit-learn==1.6.1
    - scipy==1.11.4
    - setuptools==75.8.0
    - shellingham==1.5.4
    - six==1.17.0
    - stopit==1.1.2
    - style==1.1.0
    - sympy==1.13.3
    - threadpoolctl==3.6.0
    # - torch==2.5.1
    - tqdm==4.67.1
    - typeguard==2.13.3
    - typer==0.15.2
    - typing-extensions==4.13.2
    - typing-inspect==0.9.0
    - tzdata==2025.2
    - ujson==5.10.0
    - update==0.0.1
    - urllib3==2.4.0
    - wadler-lindig==0.1.5
    - wheel==0.45.1
    - wrapt==1.17.0
    - zipp==3.21.0
